name: build exe
on: push
jobs:
  build-project:
    runs-on: windows-2019
    steps:
      - name: Checkout 
        uses: actions/checkout@v4.1.5
      - name: Install Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install python dependencies
        run: |
          pip install -r resources.txt
      - name: PyInstaller
        run: |
          python -m PyInstaller --onefile program.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: program
          path: dist/program.exe
  
